config/routes.rb
TheQuestionProject::Application.routes.draw do
  

  devise_for :users, :controllers => { :registrations => "registrations" }

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  root :to => "rounds#index"
  
  match "/about" => "pages#about"
  match "/welcome" => "pages#signed_out"
  match "/new" => "pages#new_user"
  match "/testing" => "pages#testing"
  

  resources :answers, :only => [:create, :new, :edit, :update, :index]
  resources :questions, :only => [:create, :new]
  resources :rounds, :only => [:new, :show]
  resources :pairs, :only => [:create, :new, :show, :destroy]
  resources :comments, :only => [:create, :edit, :update]
  resources :users, :only => :show
  
  resources :incoming_mails
  resources :invites, :only =>[:new, :create]
  

end

app/models/pair.rb
class Pair < ActiveRecord::Base
  validates_presence_of :user1_id, :user2_id
  belongs_to :user1, :class_name => "User"
  belongs_to :user2, :class_name => "User"
  has_many :rounds
  attr_accessible :user1_id, :user2_id
  
  # after_create :create_round
  
  def partner(user_id)
    if user_id == self.user1_id  # checking equality, comparing ids is faster then checking the user
      user2  # assigning is one equal sign, don't need to include partner =, ruby returns the last thing
    else
      user1
    end
  end

    
  def self.auto_create
    Pair.all.each do |p|
      @recent_rounds=Round.where("created_at > ? AND pair_id = ?", 30.days.ago.midnight, p.id).all

      @recent_question_ids=[]
      @recent_rounds.each do |r|
        @recent_question_ids << r.question.id
      end
      
      @question=Question.where(["id NOT IN (?)", @recent_question_ids]).sample
    
      if p.rounds.where(:round_date => Time.now.midnight).first.nil?
           @round=Round.create :question_id => @question.id, :pair_id => p.id, :round_date => Time.now.midnight
      end
           
    end
  end
  
  
  def create_round
      @pair=Pair.where(:id => self.id).first
      @question=Question.find(5)
      @round=Round.create :question_id => @question.id, :pair_id => @pair.id, :round_date => Time.now.midnight
  end
  
      
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController

before_filter :authenticate_user!
before_filter :require_no_pair, :only => [:new]

  def new
    @partners=User.where(:email => params[:email])
  end


  def create    
    @partner=User.find params[:partner_id]

    if current_user.pair.nil? && @partner.pair.nil?
      @pair=Pair.create :user1_id => current_user.id, :user2_id => params[:partner_id]
      redirect_to root_path
    else
      flash[:alert_custom]="User already has a partner!"
      redirect_to new_pair_path
    end
    
  end
  
  def show
    @pair=current_user.pair
  end
  
  def destroy
    @pair=current_user.pair
    @pair.delete
    redirect_to root_path
  end

  def require_no_pair  
     @pair=current_user.pair
     if @pair
       redirect_to root_path
     end
  end


end

app/helpers/pairs_helper.rb
module PairsHelper
  

  def search_result(partners)
    if partners.count > 0
      yield
    end
  end
  
  
  
end

app/views/pairs/new.html.erb
<% if @partners.present? %>
 <% elsif params[:email].present? %>
 
   <div class ="alert alert-warning"><%= "No results found. Try again or invite your friend to join!" %>
   <button type="button" class="close" data-dismiss="alert">&times;</button>
   </div>
 <% end %> 


 <% search_result(@partners) do %>
  <% @partners.each do |p| %>
      <h5> Friends found:</h5>
      <p class="alert alert-success"><%= p.first_name %> <%= p.last_name %> 
      <% if p.pair.nil? %> 
        <%= link_to "Select as partner", pairs_path(:partner_id => p.id), :method => "post" %></p>
      <% else %>
        <%= "(This user already has a partner)" %></p>
      <% end %>
    <% end %>
  <% end %>
     

<h4>  Want to answer questions with a partner? </h4> 
  <div class = "invite-well">
    <p><i class="icon-search">  </i>  Enter a friend's email address to search for them:</p> 
      <%= form_tag new_pair_path, :method => "get" do %>
      <%= text_area_tag :email, nil, :class => "input emailbox " %>
      <p><%= submit_tag "search", :class => "btn btn-primary" %></p>
      <% end %>
  </div>

  <div class = "invite-well">

     <i class="icon-envelope">  </i>  Or invite your friend to join The Question Project
     <div class="row">
      <div class="span4">
        <%= label_tag("Friend's email address:") %>
        <%= form_tag invites_path do %>
        <%= text_area_tag :email, nil, :class => "input emailbox" %>
      </div>
      <div class="span4">
        <%= label_tag("Add a personal message:") %>
        <%= text_area_tag :body, nil, :class => "input emailbox" %>
        <%= hidden_field_tag :kind, "partner" %>
      </div>  
    </div>
  <div class="row">
  <div class="span1">
     <p><%= submit_tag "send", :class => "btn btn-primary" %></p>
  </div>
  </div>
  <% end %>

</div>
    
    
    
  

   

app/views/pairs/show.html.erb
<p><%= "To delete your partnership with #{@pair.partner(current_user.id).first_name} #{@pair.partner(current_user.id).last_name} click the link below. There is no undo!" %></p>


<%= link_to "I understand, delete anyway", pair_path(@pair), :method => "delete"%> 