config/routes.rb
TheQuestionProject::Application.routes.draw do
  

  devise_for :users, :controllers => { :registrations => "registrations" }

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  root :to => "rounds#index"
  
  match "/about" => "pages#about"
  match "/welcome" => "pages#signed_out"
  match "/new" => "pages#new_user"
  match "/testing" => "pages#testing"
  

  resources :answers, :only => [:create, :new, :edit, :update, :index]
  resources :questions, :only => [:create, :new]
  resources :rounds, :only => [:new, :show]
  resources :pairs, :only => [:create, :new, :show, :destroy]
  resources :comments, :only => [:create, :edit, :update]
  resources :users, :only => :show
  
  resources :incoming_mails
  resources :invites, :only =>[:new, :create]
  

end

app/models/round.rb
class Round < ActiveRecord::Base
  validates_presence_of :question_id, :round_date
   belongs_to :pair
   belongs_to :question
   belongs_to :user
   has_many :answers
   has_many :comments
   attr_accessible :pair_id, :user_id, :question_id, :round_date
   
   
   def self.recent
     order("round_date DESC").where("round_date <= ?", Time.now)
   end
   
   def self.recent_minus_day
     order("round_date DESC").where("round_date <= ?", 1.day.ago.midnight)
   end
   
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  
  before_filter :require_user
  # before_filter :require_answer, :only => [:show]
  # before_filter :require_pair

#each round is a question per day for a pair, each round has a page
  
  
  def new
      @user=current_user
      @pair=@user.pair
      
      if @pair
        @recent_rounds=Round.where("created_at > ? AND pair_id = ?", 30.days.ago.midnight, @pair.id).all
      else
        @recent_rounds=Round.where("created_at > ? AND user_id = ?", 30.days.ago.midnight, @user.id).all
      end
      

      @recent_question_ids=[]
      @recent_rounds.each do |r|
        @recent_question_ids << r.question.id
      end
    
      if @recent_question_ids
        @question=Question.where(["id NOT IN (?)", @recent_question_ids]).sample
      else
        @question=Question.scoped.sample
      end
        
  end

  
  def show
    @round=Round.find params[:id]
    @question=@round.question
    @answers=@round.answers
    @comments=@round.comments
    @pair=current_user.pair
    @user=current_user
    
    # @past_day_round=@pair.rounds.where("id < ?", @round.id).first
    #     @next_day_round=@pair.rounds.where(:round_date => @round.round_date+1.day).first
    
    #a better way to do this is probably to find the next round for that pair with an id < @round.id
    # @past_day_round=@pair.rounds.where("id < ?," @round.id).first --> needs to be ordered correctly
    
    if @pair
      @future_round=@pair.rounds.where(:round_date => 1.day.from_now.midnight).first
    else
      @future_round=@user.rounds.where(:round_date => 1.day.from_now.midnight).first
      
    end

    @my_answer=@answers.where(:user_id => @user.id).first
    
  end
  

  def index
      @user=current_user
      @pair=@user.pair

      if @pair
        @partner=@pair.partner(@user.id)
      end

      # @recent_rounds=Round.where("created_at > ? AND pair_id = ?", 30.days.ago.midnight, @pair.id).all
      # 
      #      @recent_question_ids=[]
      #      @recent_rounds.each do |r|
      #        @recent_question_ids << r.question.id
      #      end
      #    
      #      
      #      if @recent_question_ids
      #        @question=Question.where(["id NOT IN (?)", @recent_question_ids]).sample
      #      else
      # end

      if flash[:new_question_id]
        @question=Question.where(:id => flash[:new_question_id]).first
        if @pair
          @rounds=@pair.rounds.recent
        else        
          @rounds=@user.rounds.recent
        end

      elsif @pair
        @rounds=@pair.rounds.recent
        @find_round=@pair.rounds.where(:round_date => Time.now.midnight).first

        if @find_round
          @my_answer=@find_round.answers.where(:user_id => @user.id).first
          @partner_answer=@find_round.answers.where(:user_id => @partner.id).first
          if @parnter_answer
            @question=@partner_answer.question
          else
        @question=Question.where("author_id IN (?)", [1, @user.id]).sample
          end
        
        else
        @question=Question.where("author_id IN (?)", [1, @user.id]).sample
        end

      
      else
        @rounds=@user.rounds.recent
        @my_round=@user.rounds.where(:round_date => Time.now.midnight).first
        @question=Question.where("author_id IN (?)", [1, @user.id]).sample
      end


    @rounds_by_month = @rounds.order("round_date DESC").group_by { |r| "#{r.round_date.month}/#{r.round_date.year}"}


  end

  
  def require_user
    redirect_to welcome_path unless current_user 
  end
  
  def require_pair  
    @pair=current_user.pair
    redirect_to new_pair_path unless @pair
 end
  
  protected 
  def require_answer
    if current_user.answers.where(:round_id => params[:id]).first.nil?
      redirect_to new_answer_path(:round_id => params[:id])
    end
  end
  
  
  
end

app/helpers/rounds_helper.rb
module RoundsHelper

  
  def comment_present(round)
    if round.comments.count > 0
      yield
    end
  end
  
  
  def comment_edit(comment)
    if comment.author == current_user
      yield
    end
  end
  
  
  def answer_edit(answer)
    if answer.user == current_user
      yield
    end
  end
         
  

  
end

app/views/rounds/index.html.erb
<script type="text/javascript">
    mixpanel.track("Home Page Loaded")
</script>




  <% if params[:question_id] %>
    <h4 align="center">Nice work answering that question!</h4>



  <% elsif @my_answer || @my_round %>
    <div class ="container">
      <h4 align="center">You've already answered a question today. Come back tomorrow!</h4>
    </div> 

  <% elsif @partner_round %>
    <div class ="container">
      <div class="span5">
        <h4><%= Time.now.to_date.to_s(:long) %></h4>
        <h3> <%= @question.body %></h3>
      </div>
      <div class="span5">
        <%= form_tag answers_path do %>
        <%= text_area_tag :body, nil, :class => "input answerbox", :maxlength =>"255" %>
        <%= submit_tag "Submit", :class => "btn" %>
        <%= hidden_field_tag :question_id, @question.id %>
         <% end %>
      </div>
    </div> 
      
  <% else %>
   <div class ="container">
      <div class="span5">
        <p><%= Time.now.to_date.to_s(:long) %></p>
        <h3> <%= @question.body %></h3>
        <div class="spacing20"></div>
        <p><%=  link_to "New question", root_path %> </p>
        <p><%=  link_to "Create your own", new_question_path %></p>
      </div>

      <div class="span5">
           <div class="spacing20">  </div>   
        <%= form_tag answers_path do %>
        <%= text_area_tag :body, nil, :class => "input answerbox", :maxlength =>"255" %>
        <%= submit_tag "Submit", :class => "btn" %>
        <%= hidden_field_tag :question_id, @question.id %>
        <% end %>
      </div>
    </div>  
           
  <% end %>


<div class="container">
  <div class="spacing20"></div>
</div>



<% @rounds_by_month.each do |round_month, rounds| %>

<% @month_name=Time.parse(round_month).strftime("%B %Y") %>
<% @month_id=Time.parse(round_month).strftime("%b") %>



  <div class="container">

    <% if Time.parse(round_month).month == "7" %>
      <h4 class="month-label" data-toggle="collapse" data-target="#<%=@month_id%>"> <%=@month_name%> <i class="icon-minus"></i></h4>
      <div id="<%=@month_id%>" class="collapse in month-item">
      
    <% else %>
      <h4 class="month-label" data-toggle="collapse" data-target="#<%=@month_id%>"> <%=@month_name%> <i class="icon-minus"></i></h4>
      <div id="<%=@month_id%>" class="collapse in month-item">
    <% end %>
          
      <% rounds.each do |r| %>
        <div class="index-well <%= @month_id.downcase%>"> 
    
      <div class="top">
        <h5><%= r.round_date.to_date.to_s(:short) %></h5>
        <p> <%= r.question.body %></p>
      </div>

      <div class="clearfix">
        <div class="bottom">
          <% if r.answers.where(:user_id => @user.id).first %>
            <p class="bottom-label"> <%= link_to "View", round_path(r) %></p>


          <% elsif @partner && r.answers.where(:user_id => @partner.id).first %>
            <p class="bottom-label"><%= link_to "#{@partner.first_name}'s answer", round_path(r) %></p>
          <% else %>
            <p class="bottom-label"><%= link_to "Answer", round_path(r) %></p>
          <% end %> 
        </div> 
      </div>
       
      </div>
  
  <% end %>
      </div>
    
  
  </div>
  
<% end %>

app/views/rounds/new.html.erb
     <% yield %>
     <% #{insert the two snippets of javascript that you get from mixpanel with your specific key} %>
     <% record_mixpanel(flash[:mixpanel_record]) # this is a custom method we've defined in application_helper.rb %> 
  
<div align="center">
      
      
      <h3> <%= @question.body %></h3>
      <p><%= Time.now.to_date.to_s(:long) %>
      <%= form_tag answers_path do %>
      <%= text_area_tag :body, nil, :class => "input answerbox roboto", :maxlength =>"255" %>
      <p><%= submit_tag "submit", :class => "btn btn-large btn-success roboto" %></p>
      <%= hidden_field_tag :question_id, @question.id %>
      <% end %>
      
      
      <div><%=  link_to "I want a different question!", new_round_path %></div>
      

      
</div>

app/views/rounds/show.html.erb
<script type="text/javascript">
    mixpanel.track("View Round")
</script>


<% if @round.answers.where(:user_id => current_user.id).present? %>
<div class = "row"> 
  <div class="span4">
    <p><%= @round.round_date.to_date.to_s(:long)%></p> 
  </div>  

</div> 


<div class="spacing20"></div>

    <h3><%= @question.body %></h3>
<% else %> 
<div class = "row"> 
  <div class="span4">
    <p><%= @round.round_date.to_date.to_s(:long) %></p>
    <h3> <%= @question.body %></h3>
  </div>
  <div class="span4">
    <%= form_tag answers_path do %>
    <p><%= text_area_tag :body, nil, :class => "input answerbox", :maxlength =>"255" %>
    <%= submit_tag "Submit", :class => "btn" %>
    <%= hidden_field_tag :question_id, @question.id %>
    <%= hidden_field_tag :round_id, @round.id %></p>
    <% end %>
  </div>
<% end %>
</div>

<div class="spacing20"></div>
    
<% @answers.each do |a| %> 
<div class="container">
  <div class="row">
    <div class="span1">
    <div class="pull-right">   
      <% if a.user.image.present? %>
      <%= image_tag a.user.image %>
      <% else %>
        <%= gravatar_for a.user, :size => 50 %>
      <% end %></div>
    </div>
    <div class="span5"> 

      <span class="name"><%= a.user.first_name %></span>
        <p><%= a.body %></p>

    </div>
      <div class="span1">
      <% answer_edit(@my_answer) do %>
      <%= link_to "edit", edit_answer_path(@my_answer), :class => "muted tiny" %>
    <% end %>
  </div> 
  </div>


<% end %>
  
<div class="spacing40"></div>

<div class="row">
  <div class ="span1">
  </div>
  <div class="span8">
      <%= form_tag comments_path do %>
      <%= text_area_tag :body, nil, :class => "input commentbox", :maxlength =>"255" %>
      <%= submit_tag "Comment", :class => "btn"%>
      <%= hidden_field_tag :round_id, @round.id %>
      <% end %>
  </div>
</div>


<% if @pair %>
  <% comment_present(@round) do %>
    <% @comments.each do |c| %>



    <div class="row">
      <div class="span1">
          <div class="pull-right">   

        <% if c.author.image.present? %>
          <%= image_tag c.author.image, :size => 40  %>
        <% else %>
          <%= gravatar_for c.author, :size => 40 %>
         <% end %>
       </div>
       </div>

      <div class="span5">

        <span class="name"><%= c.author.first_name%></span>
        <span class="muted tiny"><%= c.created_at.to_date.to_s(:short)%></span>
        <p><%= c.body %></p>


      </div> 
    
    
    </div>

      <% end %>
    <% end %>
  <% end %>
  </div>
 
  

    