config/routes.rb
TheQuestionProject::Application.routes.draw do
  

  devise_for :users, :controllers => { :registrations => "registrations" }

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  root :to => "rounds#index"
  
  match "/about" => "pages#about"
  match "/welcome" => "pages#signed_out"
  match "/new" => "pages#new_user"
  match "/testing" => "pages#testing"
  

  resources :answers, :only => [:create, :new, :edit, :update, :index]
  resources :questions, :only => [:create, :new]
  resources :rounds, :only => [:new, :show]
  resources :pairs, :only => [:create, :new, :show, :destroy]
  resources :comments, :only => [:create, :edit, :update]
  resources :users, :only => :show
  
  resources :incoming_mails
  resources :invites, :only =>[:new, :create]
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates_presence_of :body, :question_id, :user_id, :round_id
  validates :user_id, :uniqueness => { :scope => [:round_id, :question_id]}
  # validates_each :user_id do |record, attr, value|
  #     round=record.round
  #     pair=round.pair
  #     record.errors.add(attr, 'user must be in round') unless pair.user1_id == value || pair.user2_id == value
  #   end
  belongs_to :question
  belongs_to :user
  belongs_to :round
  attr_accessible :body, :question_id, :user_id, :round_id
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  before_filter :require_user, :except => :new
  before_filter :require_no_answer, :only => :new
  before_filter :protect_round,  :only => :new
    
  def new
    @question=@round.question
    @user_answers=@question.answers.where(:user_id => current_user.id)
    flash[:mixpanel_record] = "'Question Answered'"

  end
  
  def create
    @user=current_user
    @pair=current_user.pair
    @question=Question.find params[:question_id]

    if params[:round_id]
      @round=Round.find params[:round_id]
    elsif @pair
      @round=Round.where("round_date = ? AND pair_id = ?", Time.now.midnight, @pair.id).first_or_create(:question_id => @question.id, :pair_id => @pair.id, :round_date => Time.now.midnight)
    else
      @round=Round.where("round_date = ? AND user_id = ?", Time.now.midnight, @user.id).first_or_create(:question_id => @question.id, :user_id => @user.id, :round_date => Time.now.midnight)
    end
    
    if @round
      @answer=Answer.new :body => params[:body], :question_id => @question.id, :round_id => @round.id
      @answer.user=current_user
      @answer.save

      User.mail_answer(current_user, @round)
    
    redirect_to root_path(request.parameters)

    end
    
# removed redirect to new question path for now
    # @future_round=@pair.rounds.where(:round_date => 1.day.from_now.midnight).first
    # if @future_round.nil?
    #   redirect_to new_question_path
    # else
    #   redirect_to round_path(:id => params[:round_id])  
    # end

  end
  
  def index
    @answers=current_user.answers.order "created_at DESC"
    @pair=current_user.pair
  end
  
  def edit
    @answer=Answer.find params[:id]
    @round=@answer.round
    @question=@answer.question
  end
  
  def update
    @round=Round.find params[:round_id]
    @answer=Answer.find params[:id]
    @answer.body = params[:body]
    @answer.save
    redirect_to round_path(:id => @round.id)
  end


  protected 
  def require_no_answer
    if current_user.answers.where(:round_id => params[:round_id]).first
      redirect_to round_path(:id => params[:round_id])
    end
  end
  
  def protect_round
    @pair=current_user.pair
    @round=Round.where(:pair_id => @pair.id, :id => params[:round_id]).first
    redirect_to root_path if @round.nil?
  end
   
  
end
  

app/helpers/answers_helper.rb
module AnswersHelper
  
  def pair_status(round)
    @partner_name = round.pair.partner(current_user.id).first_name
    
      if round.answers.count < 1
       else
         "Submit your response to see #{@partner_name}'s answer"
      end
    
  end
    
          
end

app/views/answers/edit.html.erb
      
     <h4> <%= @question.body %></h4>

      <%= form_tag answer_path(@answer.id), :method => "put" do %>
      <%= text_area_tag :body, @answer.body, :class => "input answerbox", :maxlength =>"255"%>
      <p><a href="/answers"><%= submit_tag "Save", :class => "btn btn-primary" %></a></p>
      <%= hidden_field_tag :question_id, @question.id %>
      <%= hidden_field_tag :round_id, @round.id %>

      <% end %>
      

app/views/answers/index.html.erb
    
      <% if current_user.answers.empty? %>
        <p><%= "You don't have any answers yet!" %></p>
      <% end %>

       <% @answers.each do |a| %>
           
        <div class="well">
           <p class="roboto date tiny muted"><%= a.created_at.to_date.to_s(:long)%></p>
           <h5 class = "roboto"><%= a.question.body %></h5>
           <%= a.body %>
           <span class="edit pull-right"><%= link_to " edit", edit_answer_path(a)%></span>
         
         </div>
        <% end %>
          
        </div>

app/views/answers/new.html.erb
       <% yield %>
       <% #{insert the two snippets of javascript that you get from mixpanel with your specific key} %>
       <% record_mixpanel(flash[:mixpanel_record]) # this is a custom method we've defined in application_helper.rb %> 
    
  <div align="center">
        
        <h3> <%= @question.body %></h3>
        <p><%= @round.round_date.to_date.to_s(:long) %>
        <%= form_tag answers_path do %>
        <%= text_area_tag :body, nil, :class => "input answerbox roboto", :maxlength =>"255" %>
        <p><%= submit_tag "submit", :class => "btn btn-large btn-success roboto" %></p>
        <%= hidden_field_tag :question_id, @question.id %>
        <%= hidden_field_tag :round_id, @round.id %>
        <% end %>
  
        <p><%= pair_status(@round) %></p>
        
  </div>